var CurLocale = "ru";
var DefaultLocale = "ru";

var Strings = {
	ru: {
		Title: "Симулит-2",
		Intro: "Это немного дополненная модель из статьи <a href=\"https://www.washingtonpost.com/graphics/2020/world/corona-simulator/?utm_campaign=wp_main\">Why outbreaks like coronavirus spread exponentially, and how to “flatten the curve”</a>, автор Harry Stevens. Описанная там \"болезнь\" называется \"симулит\". Я добавила несколько дополнительных параметров и возможности настройки. И небольшую выдуманную историю, совершенно не претендующую на какое-либо отношение к реальности.",
		pBrownien: "Итак, в сказочной стране Флахландии в своих прямоугольных городах жили-были серые броуновские кружочки. Они были очень общительны и дружелюбны, бегали по своим городам и обнимались своими невидимыми руками с каждым встречным. Но однажды в одном флахладнском городе <b>Броуниэне</b> один из кружочков заболел ранее неизвестной болезнью: симулитом-2. Вместо серого он стал коричневым. И каждый серый кружочек, который встречался с коричневым, тоже заражался симулитом, становился коричневым. И всё бы ничего, большинство коричневых кружочков через некоторое время становились зелёными, и больше никого не заражали, но некоторые коричневые кружочки стали превращаться в красные крестики, а если красному крестику не помочь, он мог превратиться в чёрный крестик, а это уже навсегда. Однако, в Броуниэне ничего страшного не случилось, эльфы-целители спасли почти всех. Нажмите \"Start\",  чтобы посмотреть, как это было.",
		pBrownille: "На этом бы всё и кончилось, но беда в том, что некоторые жители Броуниэна, будучи коричневыми и ещё не зная, что это может быть опасно, разъехались по другим городам. <br/> Один из них попал в город <b>Броунвилль</b>. Но жители Броунвилля были весёлые и смелые, симулита не испугались. Что им какой-то симулит? Видали они и похуже! Тем более, вон, в Броуниэне ничего страшного не случилось! <br/>И они продолжали так же бегать по своему городу, обниматься, ходить друг к другу в гости и собирать большие застолья. Однако, в отличие от Броуниэна, в Броунвилле не было эльфов-целителей, а маленькая больница Броунвилля переполнилась, и врачи не смогли помочь всем, кому их помощь понадобилась… (Обратите внимание на сиреневую линию на графике справа)",
		pBrownhrad: "Мэр <b>Броунграда</b> очень испугался. Ему не хотелось, чтобы было как в Броунвилле, особенно накануне выборов. И он под страхом наказания запретил броунградцам выходить на улицу. Всем, кроме тех, кто разносил по домам избирательные урны. Больница Броунграда, однако, лучше не стала: врачи сидели по домам, боясь наказания, да и денег на оснащение больницы не было, все ушли на предвыборную кампанию. И ещё на церковь, чтобы молиться об удаче. Запустите симуляцию несколько раз (кнопка \"Restart\"), чтобы узнать, почему удача броунградцам так нужна.",
		pBrowntown: "А мэр <b>Броунтауна</b> был демократичным, свободолюбивым и верил в силы природы. Он не хотел ограничивать свободу жителей, и решил, что будет даже лучше, если все они станут зелёными. А чтобы не случилось беды, он призвал всех жителей дружно строить новую больницу. И они её даже построили, но…",
		pBrownburg: "До <b>Броунбурга</b> вспышка симулита добралась не сразу, и у бургомистра было время подумать и учесть опыт коллег. Он решил призвать жителей по возможности оставаться по домам, и занялся переоснащением больниц. Получилось ли у него?",
		pDiycity: "А может быть получится у вас? В <b>Даисити</b> есть кнопка \"Settings\", используйте её, чтобы менять долю жителей, остающихся дома (\"responsibility\"), начальную ёмкость больниц и скорость её увеличения. Можно менять количество жителей города, их \"размер\" и скорость — от этого меняется количество контактов каждого жителя в единицу времени и влияние самоизоляции. Можно менять и параметры болезни симулит.",
		Resume: "Эта модель очень простая. Во Флахландии нет экономики и психологии, у её жителей нет семей, друзей, коллег, они не ходят в школы, не путешествуют (кроме тех нескольких жителей Броуниэна) и не собираются на массовые мероприятия. Но даже в их мире от их действий многое зависит."
	},
en: {
		Title: "Simulitis-2",
		Intro: "This is a slightly upgraded model from the article <a href=\"https://www.washingtonpost.com/graphics/2020/world/corona-simulator/?utm_campaign=wp_main\">Why outbreaks like coronavirus spread exponentially, and how to “flatten the curve”</a> by Harry Stevens. The \"disease\" described there is called \"simulitis\". I added a couple of additional parameters and adjustable settings and a little story which doesn't pretend to do anything with reality.",
		pBrownien: "So, in a fairyland called Flatland there were grey circles in their rectangular cities. They were very communicable and friendly, ran through their cities and hugged one another with their invisible hands. But once in the city of <b>Brownien</b> one of the circles got a previously unknown disease: simulitis-2 and became brown instead of grey. Every grey circle who met a brown one, became brown, too. That wouldn't be an issue: after all, the majority of brown circles eventually became green and didn't infect anyone anymore, but some brown circles transformed into red crosses, and if one didn't help them, they became black crosses foreve. But in the city Brownien nothing bad happened, Elvish healers rescued almost everybody. Press \"Start\" to see how it happened.",
		pBrownille: "That would have been the end of the story, but the trouble is that some of the Browniennes, being brown and not knowing that this might be dangerous, went to other cities. <br/> One of them went to <b>Brownville</b>. The citizens of Brownville were cheerful and venturous and had no fear before simulitis. How bad could it be? They've seen worse! After all, in Brownian nothing bad had happened! <br/> And so they continued to run through their city, hug each other and gather for big parties. But other than in Brownian, the Brownville didn't have any Elvish healers, so the little hospital of Brownville got overcrowded, and the doctors couldn't help everybody who needed help… (Notice the purple line on the graph on the right.)",
		pBrownhrad: "The mayor of <b>Brownhrad</b> got very scared. He didn't want the situation to become a disaster like in Brownville, especially before the elections. And so, he prohibited the circles of Brownhrad to get out – all of them but the ones who carried the ballot boxes around. In Browngrade hospital, however, things didn't get better: all the doctors went home, fearing a penalty, and there was no money for the hospital as a lot was spent on the elections campaign and on the church – to pray for lick. Restart the simulation several times to know why the citizens of Browngrade actually need that much of luck.",
		pBrowntown: "The mayor of <b>Browntown</b> was very liberal and believed in the powers of nature. He didn't want to restrict the freedom of the citizens and even decided that it would be better if they all were to become green. And to avoid the worst, he asked the citizens to join their efforts in buildinf a new hospital. And they even built it, but…",
		pBrownburg: "The simulitis outbreak reached <b>Brownburg</b> a bit later, and the mayor had time to think and analyse the experience in other citites. He decided to ask the citizens to stay home if possible and simultaneously pushed for upgrading the hospitals. How well did he do?",
		pDiycity: "Maybe you will succeed? In <b>Diycity</b> there is a \"Settings\" button. Use it, to change the proportion of citizens who stay at home (\"responsibility\"), the initial hospital capacity and its growth sped. You can also adjust the number of citizens, their \"size\" and speed — this changes the number of contacts per second and the effect of isolation. You can also change the parameters of the simulitis disease.",
		Resume: "This model is extremely simple. There is no economic or psychological effects, the citizens don't have families, friends, colleagues, the don't go to schools and universities and there is no public gatherings. But still the outcome depends a lot on their behaviour."
	}
}

function getString(name) {
	var strObj = {};
	if (Strings.hasOwnProperty(CurLocale)) strObj = Strings[CurLocale]
	else strObj = Strings[DefaultLocale];
	if (strObj.hasOwnProperty(name)) return strObj[name];
	if (Strings[DefaultLocale].hasOwnProperty(name)) return Strings[DefaultLocale][name];
	return "";
	
}
